# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "ac3005cbaaec2e00beac551df933d806"
name = "abp-demo-app"
handle = "abp-demo-app"
application_url = "https://powell-workers-disks-lens.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "rocs-store.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_products,write_products"

[auth]
redirect_urls = [
  "https://powell-workers-disks-lens.trycloudflare.com/auth/callback",
  "https://powell-workers-disks-lens.trycloudflare.com/auth/shopify/callback",
  "https://powell-workers-disks-lens.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-04"

[pos]
embedded = false
